
services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "80:80"
    # user: "1000:1000"
    volumes:
      - .:/harmonie
      - /harmonie/var
      - /harmonie/vendor
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    depends_on:
      mysql:
        condition: service_started
    command: >
      sh -c "symfony composer install &&
            php bin/console doctrine:database:create --if-not-exists &&
            php bin/console doctrine:migrations:migrate --no-interaction &&
            apache2-foreground"
  websocket:
    build: ./websocket/
    ports:
      - "443:8080"
    volumes:
      - .:/harmonie
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harmonie_db 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql       # nom du service MySQL
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
  # redis:
  #   image: redis
  #   ports:
  #     # - "6379:6379"
volumes:
  mysql-data: